# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GridDiag <- function(FUNvalues, gridDim, maxdimension, decomposition, library, location, printProgress) {
    .Call('TDA_GridDiag', PACKAGE = 'TDA', FUNvalues, gridDim, maxdimension, decomposition, library, location, printProgress)
}

Bottleneck <- function(Diag1, Diag2) {
    .Call('TDA_Bottleneck', PACKAGE = 'TDA', Diag1, Diag2)
}

Wasserstein <- function(Diag1, Diag2, p) {
    .Call('TDA_Wasserstein', PACKAGE = 'TDA', Diag1, Diag2, p)
}

Kde <- function(X, Grid, h, weight, printProgress) {
    .Call('TDA_Kde', PACKAGE = 'TDA', X, Grid, h, weight, printProgress)
}

KdeDist <- function(X, Grid, h, weight, printProgress) {
    .Call('TDA_KdeDist', PACKAGE = 'TDA', X, Grid, h, weight, printProgress)
}

Dtm <- function(knnDistance, weightBound, r) {
    .Call('TDA_Dtm', PACKAGE = 'TDA', knnDistance, weightBound, r)
}

DtmWeight <- function(knnDistance, weightBound, r, knnIndex, weight) {
    .Call('TDA_DtmWeight', PACKAGE = 'TDA', knnDistance, weightBound, r, knnIndex, weight)
}

RipsDiag <- function(X, maxdimension, maxscale, dist, library, location, printProgress) {
    .Call('TDA_RipsDiag', PACKAGE = 'TDA', X, maxdimension, maxscale, dist, library, location, printProgress)
}

AlphaShapeDiagGUDHI <- function(X, printProgress) {
    .Call('TDA_AlphaShapeDiagGUDHI', PACKAGE = 'TDA', X, printProgress)
}

AlphaComplexDiagGUDHI <- function(X, printProgress) {
    .Call('TDA_AlphaComplexDiagGUDHI', PACKAGE = 'TDA', X, printProgress)
}

